### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by DoveBoy** [HearthSim/Arcane-Tracker#121]
I'm a Chinese Player.I really like Arcane-Tracker.It's a so amazing app.But it's not can select Simplified Chinese.What a pity !
I always play HearthStone on my Phone.Due to my smart phone is not rooted devices.I can't to change image resolution.  I really want the interface like on PC when play hearthstone on Phone.I want to use the Table interface.Please add the features,Players can switch the interface to Table or Phone.Thanks!

**Comment by martinbonnin** [comment]
Hi @DoveBoy. Thanks for the feedback. We'll look into simplified chinese. I'm not sure I understand what you mean by "changing the image resolution" though. Can you give more details ?
