### ISSUE TITLE
Hearthstone crashes when I use Arcane Tracker

### ISSUE THREAD

**Issue by dreqonline** [HearthSim/Arcane-Tracker#141]
Whenever I play using the tracker at some point Hearthstone crashes and I have to reopen it. Then it reconnects and hopefully I manage to reenter the game before my turn ends. This happens every single time I start a session.
If I play without starting Arcane Tracker the game doesnt crash.

Android 9
Huawei Mate 10 Pro
Arcane Tracker version 4.23

**Comment by martinbonnin** [comment]
Can you try to disable screen recording in the settings ? We've had some issues in the past with that.

**Comment by dreqonline** [comment]
Did that and had 0 crashes since then. Thanks
