### ISSUE TITLE
Arcane Tracker is no longer in the Play Store and not working with Android 11

### ISSUE THREAD

**Issue by kanamares** [HearthSim/Arcane-Tracker#153]
App not available through Play Store, and not more any updates

**Comment by martinbonnin** [comment]
Unfortunately Google has removed Arcane Tracker from the Google Play and removed file system access in Android 11, which means Arcane Tracker could not read logs any more so Arcane Tracker is not officially supported anymore. You can read more about this in the [HSReplay.net blog post](https://articles.hsreplay.net/2020/08/19/arcane-tracker-to-be-phased-out-on-august-31st/)

You can watch [github releases](https://github.com/HearthSim/Arcane-Tracker/releases). I'll keep updating cards from time to time for users that don't have Android 11 but that's the most we can do so far.

**Comment by m4tchl** [comment]
I could not find the app for 4.54 version...

**Comment by martinbonnin** [comment]
Sorry about that, the CI build failed, I just uploaded the version manually.

**Comment by l3laze** [comment]
How are cards added? It should be possible to automate the process, though it would still do well to have human review.

**Comment by martinbonnin** [comment]
It's pretty much automated, there's a script in the `script` folder if you want to tryOn Nov 7, 2020 6:53 AM, Tom <notifications@github.com> wrote:
How are cards added? It should be possible to automate the process, though it would still do well to have human review.

**Comment by D4koon** [comment]
Im no expert on android but was searching a little bit about the issue and it seems like there is a way arround it?
https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage
Other apps seem to use that as well

Not sure about a release in playstore, that i think wont change but, maybe you could use an alterative store? F-droid?

**Comment by martinbonnin** [comment]
@D4koon do you have any example of apps reading other apps files? This is not just about accessing the external directory but about reading the Hearthstone specific data in this directory.

**Comment by dnldev** [comment]
It specifically says:
Caution: After you update your app to target Android 11 (API level 30), the
system ignores the requestLegacyExternalStorage attribute
<https://developer.android.com/about/versions/11/privacy/storage#scoped-storage>
when
your app is running on Android 11 devices, so your app must be ready to
support scoped storage and to migrate app data
<https://developer.android.com/training/data-storage/use-cases#migrate-legacy-storage>
for
users on those devices.

Which makes it clear why the app will not be able to be supported in
Android 11 unless they add a new way to ask for that dangerous permission.

**Comment by martinbonnin** [comment]
Yup, this is what I had in mind too. Also from https://developer.android.com/about/versions/11/privacy/storage#other-app-specific-dirs:

```
On Android 11, apps can no longer access files in any other app's dedicated, app-specific directory within external storage.
```

**Comment by UndarkAido** [comment]
Solid Explorer can access these logs on Android 11. Is that what y'all need?
![Screenshot_20210331-212003](https://user-images.githubusercontent.com/7421794/113234443-e159a480-9266-11eb-9e13-8138ccaebdae.png)

**Comment by martinbonnin** [comment]
@UndarkAido Do you mind sharing the full path from the root of the filesystem and your OS version? 
Also double-checking: you didn't root your phone, right?

**Comment by UndarkAido** [comment]
@martinbonnin
`/storage/emulated/0/Android/data/com.blizzard.wtcg.hearthstone/files/Logs`
Pixel 4XL running Android 11 build Rq2A.210305.006
Unrooted

**Comment by martinbonnin** [comment]
Interesting... I can't seem to access this. I have "Internal Memory", which I believe should map to `/storage/emulated/0/` but somehow can't get to `com.blizzard.wtcg.hearthstone`

**Comment by D4koon** [comment]
Today i tried it too and it also worked
Solid Explorer told me so i have to grant access to the folder as can be seen in the following picture:
<img src="https://user-images.githubusercontent.com/13141819/113410811-9352b700-93b4-11eb-931a-a140fa29dfae.jpg" width="60%" height="60%">

After that i could acces the logs with the app:
<img src="https://user-images.githubusercontent.com/13141819/113410868-b1b8b280-93b4-11eb-8500-53e7dcae167c.jpg" width="60%" height="60%">

**Comment by martinbonnin** [comment]
Thanks! I can reproduce too. I'll dig to see how they were able to do this.

**Comment by martinbonnin** [comment]
Good news: there's a trick to get access to the Hearthstone logs 🎉 . It's documented there: https://stackoverflow.com/questions/65967690/how-do-some-apps-reach-the-contents-of-android-sub-folders-on-android. 
Bad news: it looks painfully slow to the point where tracking lags several minutes. If anyone's curious, the branch is at https://github.com/HearthSim/Arcane-Tracker/tree/saf

I'll keep digging to see if that can be optimized somehow. Overall, that trick really looks like an oversight from Google. Not sure how long it will take before they patch it but if I can make the tracker work reliably on Android 11, I'll make a release

**Comment by UndarkAido** [comment]
@martinbonnin Is that the way Solid does it? If I'm remembering right I think it did something where Android asked me what folder to give it access to and I just told it the SD root?

**Comment by martinbonnin** [comment]
Yep, same kind of things I believe. Somehow passing the `INITIAL_URL` is the key to getting access to `Android/data` and `Android/obb`.

**Comment by martinbonnin** [comment]
And tentative version using the workaround and the storage access framework is live: https://github.com/HearthSim/Arcane-Tracker/releases/tag/461

It is working on my ~machine~ phone (™️) but I'm not 100% sure how this is supposed to work so please report how that worked for you.

**Comment by knpk13** [comment]
Was greeted by a prompt to grant access to the HS folder on first launch.
Tracker lagged really hard and froze after granting access. Eventually
started responding and queued up button presses started running. Restarted
the tracker and played a few games. Card/hand tracking and win/loss
tracking is working fine at the very least. Thank you!

Tested on a OnePlus 7T Pro, Android 11 (OOS 11)

Can provide logs if needed.

**Comment by D4koon** [comment]
For me it also doesn't work.
Is there a debug mode or log that can be displayed?

**Comment by Esheep57** [comment]
Doesn't work on Pixel 5
:/

**Comment by vincentBesseau** [comment]
Hi @martinbonnin ,
I tryed your test version (https://github.com/HearthSim/Arcane-Tracker/releases/tag/461) on my One Plus 8 pro not rooted.
It seem work but when I am on game I see my deck but it was not refresh when I draw or play a card.

**Comment by Otto42** [comment]
Works on a Pixel 4XL, running Android 11. No noticable lag in detecting the plays that I can see.

**Comment by ex4722** [comment]
> Works on a Pixel 4XL, running Android 11. No noticeable lag in detecting the plays that I can see.

Where did you install the initial log file to? I tired the default spot and it cant seem to detect any of the game changes. I can see the current deck but not the opponent one

**Comment by knpk13** [comment]
It's a little buggy at times. I installed it to the default location it
picked, I'd have to check again if you really need the path. I experience
the same bug as you occasionally, and I just close and restart the tracker
when that happens and it starts working again. Not ideal, but it's a
workaround.

**Comment by ScottAllen11** [comment]
Was working on my Galaxy A50. Changed to an S21. Not seeing the logs. I can find them manually with Total Commander. I'm not sure if I set the right permission location for Arcane Tracker. How can I check it or reset it? Reinstalled but it didn't ask again.

**Comment by knpk13** [comment]
Clear external storage access permission, it will prompt you to grant
access again when you open the app.

**Comment by ScottAllen11** [comment]
The marker file is in that same folder. So is log.config but it is also 0 bytes. I do want to use the "files" folder under com.blizzard.wtcg.hearthstone, correct? I've cleared the external permissions.

**Comment by stormerider** [comment]
Should I try testing this on a device still using Android 10? Not sure if that would be helpful, but I'm looking at migrating from my Tab S6 to an S7 in the future and want to help this any way I can.

**Comment by stormerider** [comment]
So I updated my S6 to Android 11 and wasn't able to get this to work. Somehow it was only getting media access to storage, not file access. I did get the S7+ like I planned, and upgraded that to 11 and everything works like before (practice mode doesn't accurately track decks, but that's a known issue, I believe, similar to Duels).

I was doing some reading up on scoped storage and there's a new permission that was recently added, MANAGE_EXTERNAL_STORAGE. https://www.xda-developers.com/android-11-all-files-access-permission-form/ has details. That might be a long term workaround, as it's intended to do what we're trying here, rather than the slower method that looks more like an oversight.

Now, I doubt you'd get approval to use it on the Play Store, but if you're continuing to release APKs, it shouldn't be an issue.

**Comment by stormerider** [comment]
I spoke too soon. Not sure what changed (maybe just rebooting the devic3?), but it's back to media only permission on the S7+. Any luck with a build using the flag I dug up?

**Comment by alexbarg3000** [comment]
Is new version for miniset coming any time soon?

**Comment by stormerider** [comment]
So I was finally able to get things building locally and I was able to test the permission changes I mentioned earlier. By adding the `MANAGE_EXTERNAL_STORAGE` permission (which required bumping `compileSdkVersion` to 30) in the various XML manifest files and Kotlin files that check permissions, I was able to get things up and running again on my Android 11 tablet. You need to double check that the permission actually takes, as I saw some occurrences where it got past the initial loading screens that prompt you for permissions, but when checking the status of the app, access was denied. It should show with "Allow management of all files" for the storage permission. I've got a branch up here: https://github.com/stormerider/Arcane-Tracker/tree/android11

**Comment by kanamares** [comment]
Team already working on this

**Comment by alexbarg3000** [comment]
If you start the game using tracker, it doesn't work and you have to close the tracker and start it again once the game is running. this wasn't a problem before. Now tracker constantly crashes and needs restarting manually. Also. tracker randomly starts itself for no reason and runs in the background. Android 10

**Comment by stormerider** [comment]
I haven’t had any crashes, but I’m seeing the other issues reported by @alexbarg3000 .

**Comment by martinbonnin** [comment]
Hi everyone 👋 

@kaluokeda maintains an alternate tracker at https://github.com/keluokeda/hs_tracker. It's not on the Google Play but you can download the apk from the releases page. 

I haven't looked at the code myself so this is not any form endorsement of the tracker (in other words, use at your own risks). But if you're looking for a functional and maintained tracker for Android, that might be your chance!

**Comment by jasmeralia** [comment]
Looks like that project disappeared. I think I have a cchecked out copy, but I'll have to confirm.

**Comment by martinbonnin** [comment]
That project did disappear indeed 🤷

**Comment by CognitiveMango** [comment]
Huh, wonder what happened. I do have a copy of the APK saved, but didn't
feel comfortable granting it the requested permissions so haven't tested
it. I was going to wait for you to look over the code and endorse it before
I tested it just to be safe lol.

**Comment by martinbonnin** [comment]
>  I was going to wait for you to look over the code and endorse it before I tested it just to be safe lol

Don't hold your breath there. I don't have much time left for Hearthstone stuff these days. A thorough audit is a huge project. The fact that the repo disappeared isn't a great sign TBH so yea, "use at your own risk" is going to be the mantra.
