### ISSUE TITLE
Stats screen no longer recording new games

### ISSUE THREAD

**Issue by nomadfarmer** [HearthSim/Arcane-Tracker#155]
The info on the stats page no longer includes new games. After a game ends, the record beside the deck name on the blue button updates, but the game is not added under games and the relevant deck under stats is not updated.

I know that replays being sent to hsreplay.net has lasted much longer than promised, but is the loss of stats within the app expected?

Thanks for everything.

**Comment by martinbonnin** [comment]
Can you try version 456? https://github.com/HearthSim/Arcane-Tracker/releases/tag/456

**Comment by martinbonnin** [comment]
Closing in favor of https://github.com/HearthSim/Arcane-Tracker/issues/157, please post updates there if needed
