### ISSUE TITLE
Arena games stopped uploading to hsreplay.net

### ISSUE THREAD

**Issue by cybergollum** [HearthSim/Arcane-Tracker#156]
The bug appeared after last update (455).

Games are no longer added to Arcane Tracker game history too.

**Comment by mariodmmariodm** [comment]
even in ranked does not update replays

**Comment by martinbonnin** [comment]
Yep, I'm quasi-certain this comes from the new ranking system that does not output the [GOLD_REWARD_STATE](https://github.com/HearthSim/Arcane-Tracker/blob/62b9a9bf55c3475fa6a29d3239ed48a4bb5f3b86/kotlin-hslog/src/commonMain/kotlin/net/hearthsim/hslog/parser/power/RawGameHandler.kt#L33) lines any more. I'll try to take a quick look how fixable that is.

**Comment by mariodmmariodm** [comment]
Hi Martin! The new secrets of the magician, and I guess others are not revealed in the special function ...

**Comment by martinbonnin** [comment]
New version there: https://github.com/HearthSim/Arcane-Tracker/releases/tag/456

I've tested it and history/uploads seems to work again but I have very limited time to work on Arcane Tracker so can't guarantee anything will work 100%. Anyways, let me know if it worked

**Comment by martinbonnin** [comment]
Closing in favor of https://github.com/HearthSim/Arcane-Tracker/issues/157, please post updates there if needed
