### ISSUE TITLE
Darkmoon Faire Secrets

### ISSUE THREAD

**Issue by jk2112** [HearthSim/Arcane-Tracker#158]
Darkmoon Faire secrets don't appear in the Arcane Tracker secret tracker. I'd like to develop this myself if there are no plans for it, to help support this project. Is this where I get approval?

**Comment by martinbonnin** [comment]
>  Is this where I get approval?

Yup, you've come to the right place. Feel free to open a pull request.

**Comment by l3laze** [comment]
Any progress on this? I know the mini-set is a week away anyways, but still.


Is this something that could be automated to make updates more simple?

**Comment by martinbonnin** [comment]
Hello 👋 

> Any progress on this?

Version 458 is just released: https://github.com/HearthSim/Arcane-Tracker/releases/tag/458

> Is this something that could be automated to make updates more simple?

There's a `./script/update_card_json.kt` that automates a bunch of things but the actual logic of how secret work will always have to be manually implemented.

**Comment by l3laze** [comment]
Yeah, I realized that shortly after I asked, lol. I'm sorry.
