### ISSUE TITLE
Note 20 ultra Won't detect game 

### ISSUE THREAD

**Issue by AlShegardy** [HearthSim/Arcane-Tracker#160]
My phone just updated to one ui 3. And immediately afterwards arcane tracker stopped detecting that hearthstone is open. No deck list for me or the opponent.

**Comment by martinbonnin** [comment]
If One UI 3 uses Android 11 this is unfortunately expected, Google tightened the security restrictions so that Arcane Tracker (and other apps) cannot read logs. See https://github.com/HearthSim/Arcane-Tracker/issues/153 for more details.

**Comment by AlShegardy** [comment]
It does use Android 11. Thank you for the fast reply.

**Comment by martinbonnin** [comment]
I wish there were a better answer but unfortunately Google is taking the iOS road of restricting what apps can do more and more..
