### ISSUE TITLE
Games are not recorded

### ISSUE THREAD

**Issue by Maximm6987** [HearthSim/Arcane-Tracker#161]

**Comment by martinbonnin** [comment]
Can you please specify your version?

**Comment by Maximm6987** [comment]
Yes, sorry. The latest release on android 10.

**Comment by martinbonnin** [comment]
I'm assuming version 459 then ?

**Comment by Maximm6987** [comment]
Yes, I ment the latest release of arcane tracker. Once again sorry for not being clear.

**Comment by Maximm6987** [comment]
Update, it works suddenly. Thanks for the wonderful tracker.
