### ISSUE TITLE
I hate that Android support is going away!

### ISSUE THREAD

**Issue by enkode** [HearthSim/Arcane-Tracker#168]
I just want to tell you guys this app will be truly missed by a few hardcore fans. I appreciate the dev team and maybe some alternative will come out soon. This was a one of a kind app.

**Comment by AleksanderStefankowski** [comment]
Thumbs up!

Glad I ignore the permanent prompt to upgrade android version on my smasung S10+, I still have android 9 with One UI 1.1

Great phone.

**Comment by knpk13** [comment]
GitHub issues aren't really the place to discuss these opinions (without
anything useful like proposing a solution/pull request or bug report) about
apps. It tends to be demoralizing, especially when the dev has given an
explanation for why support isn't present.

That said, a build with Android 11 support was pushed out recently and I've
been using it and it works fine.

**Comment by AleksanderStefankowski** [comment]
@enkode I guess you can close this issue then! :)
