### ISSUE TITLE
Difficulties getting the trackobot password

### ISSUE THREAD

**Issue by Duerkos** [HearthSim/Arcane-Tracker#2]
Account login is not working for me.

It asks for Username and Password, but if you have an account created on track-o-bot there is no login/password, there is an access token for API purposes.

Strangely enough, if you create the account from arcane tracker, you can login on trackobot/profile. But this way does not allow you to sync with the windows program, since you cannot import any file.

**Comment by martinbonnin** [comment]
Can you try entering your access token in the password field ?

**Comment by Duerkos** [comment]
Yes, I tried but it shows an error. With the track-o-bot app that shows stats it happens the same...

**Comment by Duerkos** [comment]
This seems to be related:

[https://github.com/stevschmid/track-o-bot/issues/179](https://github.com/stevschmid/track-o-bot/issues/179)

PD: Whatever! I found the fix.

The issue is that password != access token. I am guessing that access token is only useful for "viewing" information, not uploading.

If you create the account on PC/MAC, then export the profile, then read that profile file with notepad++ you will get the password.

It is stored in this format:

 & acount - name - 0 0 0 0    password   * h t t p s : / / t r a c k o b o t . c o m

I could not read it, there were a lot of NULL symbols but doing a simple copy paste I was able to extract the real password, and it works!

I am guessing you could create the profile file to export it to PC from the android app with this information as well.

**Comment by andrewisliving** [comment]
I can't figure out how to "export the profile." I'm on a Mac but have an Android phone. How can I do this?

**Comment by martinbonnin** [comment]
@andrewisliving 

* on your mac, click the trackobot icon in the notification area, then go to settings. You should have an option to export your account (I'm saying this from memory, I don't have a Mac). 
* download the latest beta or Arcane Tracker (https://play.google.com/apps/testing/net.mbonnin.arcanetracker), put the .track-o-bot file at the root of your phone
* go to Arcane tracker settings and click 'import account from storage'. That should import your account.

**Comment by andrewisliving** [comment]
@martinbonnin Thank you so much!!

**Comment by livejamie** [comment]
@Duerkos @martinbonnin 

So for my export, it's:

`    ( t h r o b b i n g - g n o l l - 1 2 3 4    3 a e 5 2 0 8 4 9 b   * h t t p s : / / t r a c k o b o t . c o m`

(I changed a bunch of the numbers for security reasons)

What would the correct username and password be here?

**Comment by martinbonnin** [comment]
Wild guess:

username: throbbing-gnoll-1234
password: 3ae520849b

Maybe add '*' at the end of the password if it doesn't work

**Comment by livejamie** [comment]
If I don't put in the asterisk the settings seem to take the login but when I click on open external profile it says "Unauthorized" in the browser. Does that mean it's still working?

If I put in the asterisk it just shows the spinner for a long time and doesn't seem to take the login.

If I close out the settings and click "Open Profile" it says it can't find the link.

**Comment by martinbonnin** [comment]
Have you tried the 'import track-o-bot" file option ? It might suit your needs better. Just drop your .track-o-bot file under /sdcard

**Comment by livejamie** [comment]
My device doesn't have a sdcard

**Comment by martinbonnin** [comment]
All android devices I know have a folder called /sdcard, even if they don't have a physical sdcard. Try with a file explorer like astro: https://play.google.com/store/apps/details?id=com.metago.astro&hl=en

**Comment by livejamie** [comment]
I was able to import it successfully but I'm still getting "Unauthorized" when trying to open my external profile. Does it work for others, should I open a separate bug?

**Comment by martinbonnin** [comment]
Please open a separate bug and send a feedback after trying to open your profile from settings -> send feedback. Or if you don't mind to PM you .track-o-bot file to support@arcanetracker.com, that'll speed up the debugging quite a bit (for what it's worth, I promise I won't touch anything there)

**Comment by livejamie** [comment]
Sure I'll email it to you.
