### ISSUE TITLE
Not recognizing Amazon Underground' Hearthstone

### ISSUE THREAD

**Issue by CloudscrapeR86** [HearthSim/Arcane-Tracker#29]
I have a p9 Lite.

I use hearthstone downloaded from Amazon Underground to be able to buy stuff with amazon coins.

Whenever I start Arcane Tracker, it says that it was not able to find my hearthstone installation folder.

Let me know if you need more data.

**Comment by martinbonnin** [comment]
Can you try to subscribe to the beta version ? https://play.google.com/apps/testing/net.mbonnin.arcanetracker. 

If it's still not working, we would need the path to the Hearthstone log files. Something like:

/Android/data/com.blizzard.wtcg.hearthstone/files/Log

**Comment by ThaWeatherman** [comment]
I use the Amazon Underground install and have no issue with Arcane Tracker. It probably has something to do with how you installed it.
