### ISSUE TITLE
Fireside Gathering games not reporting to Track-o-Bot

### ISSUE THREAD

**Issue by nothingatall544** [HearthSim/Arcane-Tracker#59]
Situation:
1) Connect Track-o-Bot account to Arcane Tracker
2) Be on lan at a Fireside Gathering connected to the firesides network
3) Challenge someone at the event to play Standard through the Fireside nearby opponents menu
4) Play game

Expected result:
Game results for the night have been uploaded to Track-o-Bot in the game history tab

Actual result:
None of the games have been uploaded :(

Other info:
I attend local Fireside Gathering tournaments and was really hoping to be able to review results later that night.

I would guess that this type of game has a different game mode attached to it in the logs, I can grab my logfiles on Sunday if that would help with debugging

Thanks

**Comment by martinbonnin** [comment]
Thanks for the feedback. Indeed log files would be very useful. Next time this happens, you can click settings -> send feedback. That'll send the hs logs as well as some arcane tracker ones.
